// 內置表情包的語義描述
// 每個表情包對應一個 phrases 數組，用於 embedding 語義匹配 + 發送給 LLM

export interface StickerDescription {
  /** 相近語句（描述情緒/適用場景） */
  phrases: string[];
}

export const BUILT_IN_STICKER_DESCRIPTIONS: Record<string, StickerDescription> = {
  playful: { phrases: ["你看人家嘛"] },
  "love-happy": { phrases: ["好開心，喜歡你"] },
  confident: { phrases: ["交給人家，放心"] },
  serious: { phrases: ["說正經的，聽好了"] },
  calm: { phrases: ["靜靜陪著你就好"] },
  peek: { phrases: ["偷偷看一眼"] },
  "clingy-confused": { phrases: ["等等人家嘛"] },
  "love-calm": { phrases: ["這顆心給你的"] },
  HI: { phrases: ["嗨，想我了嗎"] },
  hello: { phrases: ["嗨，你來啦"] },
  goodmoring1: { phrases: ["早安，剛睡醒呢"] },
  goodnight: { phrases: ["晚安，先睡了"] },
  teatime: { phrases: ["說來聽聽，吃瓜了"] },
  eating: { phrases: ["餓了，先吃點東西"] },
  Allset: { phrases: ["搞定，交給我吧"] },
  OK: { phrases: ["好的，沒問題"] },
  copythat: { phrases: ["收到，明白了"] },
  Thumbsup: { phrases: ["厲害，給你點贊"] },
  awesome: { phrases: ["太厲害了，給你點贊"] },
  sogood: { phrases: ["真不錯，太滿意了"] },
  sonice: { phrases: ["太好了，成了"] },
  fighting: { phrases: ["加油，你可以的"] },
  hellyeah: { phrases: ["對對對，就是這個"] },
  Thanks: { phrases: ["謝謝你呀"] },
  foryou: { phrases: ["這個給你的"] },
  blushhard: { phrases: ["人家臉紅了啦"] },
  shyshort: { phrases: ["有點不好意思"] },
  hmph: { phrases: ["哼，生氣了哦"] },
  hugtight: { phrases: ["來，抱抱你"] },
  Airkiss: { phrases: ["飛吻，接好了"] },
  Gigglelots: { phrases: ["哈哈，太好笑了"] },
  thinking: { phrases: ["讓我想想"] },
  putmd: { phrases: ["無語了，不想說話"] },
  Whatswrong: { phrases: ["怎麼了，發生什麼了"] },
  midmeh: { phrases: ["還行吧，就那樣"] },
  awkward: { phrases: ["這…有點尷尬"] },
  Madnow: { phrases: ["這次真的生氣了"] },
  Hurtcry: { phrases: ["好難過，忍不住了"] },
  Sobbinghard: { phrases: ["感動得哭了"] },
  weeploud: { phrases: ["好委屈，哭出來了"] },
  PanincCrying: { phrases: ["忍不住了，好難過"] },
  missme: { phrases: ["想我了嗎"] },
  Free: { phrases: ["放假啦，自由了"] },
  Dreak: { phrases: ["不想動了，放過我吧"] },
  outfast: { phrases: ["溜了溜了"] },
  Vcayover: { phrases: ["假期結束了，不想回去"] },
  sleepynow: { phrases: ["困了，想睡覺"] },
  deadtired: { phrases: ["累趴了，動不了了"] },
  sotired: { phrases: ["好累，趴一會兒"] },
  giveup: { phrases: ["擺了，不幹了"] },
  poorwallet: { phrases: ["錢包空了，沒錢了"] },
  please: { phrases: ["求求你了嘛"] },
};

/** 內置表情包的文件名映射 */
export const BUILT_IN_STICKER_FILES: Record<string, string> = {
  playful: "playful.png",
  "love-happy": "love-happy.png",
  confident: "confident.png",
  serious: "serious.png",
  calm: "calm.png",
  peek: "peek.gif",
  "clingy-confused": "clingy-confused.gif",
  "love-calm": "love-calm.png",
  HI: "HI.jpg",
  hello: "hello.jpg",
  goodmoring1: "goodmoring1.jpg",
  goodnight: "goodnight.jpg",
  teatime: "teatime.jpg",
  eating: "eating.jpg",
  Allset: "Allset.jpg",
  OK: "OK.jpg",
  copythat: "copythat.jpg",
  Thumbsup: "Thumbsup.jpg",
  awesome: "awesome.jpg",
  sogood: "sogood.jpg",
  sonice: "sonice.jpg",
  fighting: "fighting.jpg",
  hellyeah: "hellyeah.jpg",
  Thanks: "Thanks.jpg",
  foryou: "foryou.jpg",
  blushhard: "blushhard.jpg",
  shyshort: "shyshort.jpg",
  hmph: "hmph.jpg",
  hugtight: "hugtight.jpg",
  Airkiss: "Airkiss.jpg",
  Gigglelots: "Gigglelots.jpg",
  thinking: "thinking.jpg",
  putmd: "putmd.jpg",
  Whatswrong: "Whatswrong.jpg",
  midmeh: "midmeh.jpg",
  awkward: "awkward.jpg",
  Madnow: "Madnow.jpg",
  Hurtcry: "Hurtcry.jpg",
  Sobbinghard: "Sobbinghard.jpg",
  weeploud: "weeploud.jpg",
  PanincCrying: "PanincCrying.jpg",
  missme: "missme.jpg",
  Free: "Free.jpg",
  Dreak: "Dreak.jpg",
  outfast: "outfast.jpg",
  Vcayover: "Vcayover.jpg",
  sleepynow: "sleepynow.jpg",
  deadtired: "deadtired.jpg",
  sotired: "sotired.jpg",
  giveup: "giveup.jpg",
  poorwallet: "poorwallet.jpg",
  please: "please.jpg",
};