export interface CyreneQuizQuestion {
  id: string;
  category: string;
  prompt: string;
  options: [string, string, string, string];
  answer: number;
  explanation: string;
  spoiler: boolean;
}

export const CYRENE_QUIZ_SOURCE = "https://zh.moegirl.org.cn/zh-tw/%E6%98%94%E6%B6%9F";

export const CYRENE_QUIZ_QUESTIONS: CyreneQuizQuestion[] = [
  {
    id: "element",
    category: "基本資料",
    prompt: "昔漣在遊戲中的屬性是？",
    options: ["火", "冰", "量子", "風"],
    answer: 1,
    explanation: "昔漣是冰屬性角色。",
    spoiler: false,
  },
  {
    id: "path",
    category: "基本資料",
    prompt: "昔漣行於哪一條命途？",
    options: ["同諧", "記憶", "智識", "豐饒"],
    answer: 1,
    explanation: "她行於「記憶」命途，角色意象也始終圍繞記得、書寫與回望。",
    spoiler: false,
  },
  {
    id: "origin",
    category: "人物檔案",
    prompt: "昔漣的出身地區是？",
    options: ["匹諾康尼", "翁法羅斯", "雅利洛－Ⅵ", "仙舟羅浮"],
    answer: 1,
    explanation: "她來自翁法羅斯，與這個世界的記憶緊密相連。",
    spoiler: false,
  },
  {
    id: "voice",
    category: "人物檔案",
    prompt: "昔漣的漢語配音演員是？",
    options: ["宴寧", "花玲", "杜冥鴉", "陳婷婷"],
    answer: 0,
    explanation: "昔漣的漢語配音由宴寧擔任。",
    spoiler: false,
  },
  {
    id: "eyes",
    category: "外觀印象",
    prompt: "昔漣的瞳色主要是？",
    options: ["金色", "紅色", "藍色", "紫色"],
    answer: 2,
    explanation: "她的眼睛以藍色為主，瞳孔帶有鮮明的菱形特色。",
    spoiler: false,
  },
  {
    id: "location",
    category: "人物檔案",
    prompt: "昔漣的常駐位置位於何處？",
    options: ["奧赫瑪廣場", "哀麗秘榭－遠行渡口", "創世渦心", "星穹列車觀景車廂"],
    answer: 1,
    explanation: "資料頁列出的常駐位置是哀麗秘榭的遠行渡口。",
    spoiler: false,
  },
  {
    id: "coauthor",
    category: "人物關係",
    prompt: "誰是《如我所書》的共同主筆？",
    options: ["白厄", "開拓者", "黑塔", "三月七"],
    answer: 1,
    explanation: "開拓者既是昔漣的夥伴，也是《如我所書》的共同主筆。",
    spoiler: false,
  },
  {
    id: "childhood",
    category: "人物關係",
    prompt: "昔漣的青梅竹馬是誰？",
    options: ["萬敵", "白厄", "阿那克薩戈拉斯", "賽飛兒"],
    answer: 1,
    explanation: "人物關係中，白厄被列為昔漣的青梅竹馬。",
    spoiler: false,
  },
  {
    id: "base-form",
    category: "人物關係",
    prompt: "昔漣誕生後的基礎形態叫什麼？",
    options: ["迷迷", "緹寶", "德謬歌", "長夜月"],
    answer: 0,
    explanation: "迷迷是她誕生後的基礎形態。",
    spoiler: false,
  },
  {
    id: "nickname",
    category: "角色印象",
    prompt: "下列哪一個是昔漣常見的別號？",
    options: ["小海兔", "小灰毛", "小孔雀", "小浣熊"],
    answer: 0,
    explanation: "「小海兔」是資料頁列出的昔漣別號之一。",
    spoiler: false,
  },
  {
    id: "pen-name",
    category: "回憶深處",
    prompt: "「昔漣」這個名字最初是什麼？",
    options: ["故鄉的地名", "第一次寫詩時取的筆名", "白厄替她取的名字", "泰坦賜予的稱號"],
    answer: 1,
    explanation: "少女形態的她第一次寫詩時，為自己取了「昔漣」這個筆名。",
    spoiler: true,
  },
  {
    id: "forms-count",
    category: "存在形式",
    prompt: "資料中將昔漣本體整理為幾種主要存在形式？",
    options: ["兩種", "三種", "四種", "十三種"],
    answer: 2,
    explanation: "記憶的種子、迷迷、少女形態與完全體被整理為四種存在形式。",
    spoiler: true,
  },
  {
    id: "forms-order",
    category: "存在形式",
    prompt: "四種形式對應的成長順序是？",
    options: ["種子→幼苗→花蕾→記憶之花", "幼苗→種子→果實→花蕾", "花蕾→幼苗→種子→記憶之花", "種子→花蕾→幼苗→記憶之花"],
    answer: 0,
    explanation: "官方文本意象依序是記憶的種子、幼苗、花蕾與記憶之花。",
    spoiler: true,
  },
  {
    id: "teacher",
    category: "角色經歷",
    prompt: "昔漣曾在奧赫瑪從事什麼工作？",
    options: ["鍛造兵器", "教孩子識字與講故事", "管理港口", "研究天象"],
    answer: 1,
    explanation: "她曾在奧赫瑪教孩子們識字，也向他們講述逐火的故事。",
    spoiler: true,
  },
  {
    id: "waiting",
    category: "角色經歷",
    prompt: "昔漣從光歷3960年等待到哪一年？",
    options: ["光歷4123年", "光歷4540年", "光歷4931年", "光歷5000年"],
    answer: 2,
    explanation: "她一直等待到光歷4931年，跨越了近千年的時光。",
    spoiler: true,
  },
  {
    id: "memory-dependence",
    category: "存在形式",
    prompt: "作為記憶模因存在時，昔漣最直接依附於什麼？",
    options: ["黑塔的模擬宇宙", "開拓者的記憶", "白厄的火種", "星穹列車的資料庫"],
    answer: 1,
    explanation: "這一存在形式依附於開拓者的記憶，遺忘也因此成為真正的消失風險。",
    spoiler: true,
  },
  {
    id: "record-book",
    category: "角色經歷",
    prompt: "昔漣用哪一本書記錄舊識與黃金裔的故事？",
    options: ["《如我所書》", "《一頁永恆》", "《黃金史詩》", "《歲月之書》"],
    answer: 0,
    explanation: "她將眾人的事跡記入《如我所書》，讓故事繼續被記得。",
    spoiler: true,
  },
  {
    id: "complete-form",
    category: "存在形式",
    prompt: "完全體形態在成長意象中被稱作什麼？",
    options: ["記憶的果實", "記憶的花", "記憶的湖", "記憶的漣漪"],
    answer: 1,
    explanation: "完全體對應「記憶的花」，象徵記憶量級與完成度達到完整狀態。",
    spoiler: true,
  },
  {
    id: "origin-seed",
    category: "真相回望",
    prompt: "昔漣的本源最接近下列哪一項？",
    options: ["第十三因子與翁法羅斯之心", "星神浮黎的碎片", "列車資料庫的投影", "庭院中的普通花朵"],
    answer: 0,
    explanation: "資料將她的本源連結到原本應成為第十三因子的最初智種，也就是翁法羅斯之心。",
    spoiler: true,
  },
  {
    id: "dream",
    category: "角色經歷",
    prompt: "漫長等待中，昔漣曾夢見自己和誰一起旅行？",
    options: ["假面愚者", "星穹列車組", "天才俱樂部", "公司戰略投資部"],
    answer: 1,
    explanation: "她曾夢見自己登上星穹列車，與列車組一同踏上開拓旅程。",
    spoiler: true,
  },
];
